# Generated by Django 3.2.4 on 2021-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0009_certificado_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='situacao',
            field=models.SmallIntegerField(default=2),
        ),
    ]
