# Generated by Django 3.2.4 on 2021-09-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0011_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certificados.curso'),
            preserve_default=False,
        ),
    ]
