# Generated by Django 3.2.4 on 2021-09-20 04:24

import certificados.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0014_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.FileField(upload_to='certificados/', validators=[certificados.validators.validate_file_extension]),
        ),
    ]
